### ISSUE TITLE
Version 15

### ISSUE THREAD

**Issue by agritheory** [agritheory/beam#87]
Add V15 to CI test matrix

**Comment by HKuz** [comment]
`version-15` branch pushed up to repo (no PR since it's a new base branch)

- [x] CI passing (see actions tab)
- [x] v15.0.0 tag/release created
- [x] successfully installed locally in a v15 bench with a few tweaks to `tests/setup.py` and `install.py`
- [x] create new BEAM Settings doctype to split out settings/assumptions -> see PR #96

**Comment by agritheory** [comment]
@HKuz For now the setting I'm certain we want to add is a per-company opt-out of handling units. Other settings can follow.
